{{- if .Values.experimentalGcsFuse.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rpc.fullname"  . }}-data-volume-pvc
  {{- if .Values.experimentalGcsFuse.annotations }}
  annotations:
{{ toYaml .Values.experimentalGcsFuse.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "rpc.labels" . | nindent 4 }}
spec:
  accessModes:
{{ toYaml .Values.experimentalGcsFuse.accessModes | indent 4 }}
  storageClassName: {{ default "csi-gcs" .Values.experimentalGcsFuse.storageClass }}
  resources:
    requests:
      storage: "{{ .Values.experimentalGcsFuse.storage }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rpc.fullname"  . }}-config-volume-pvc
  annotations:
  labels:
    {{- include "rpc.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rpc.fullname"  . }}-cosmovisor-volume-pvc
  annotations:
  labels:
    {{- include "rpc.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: "1Gi"
{{- end -}}